/**
 * This file is automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND.
 * Instead, modify your Payload config or collections and regenerate.
 */

export interface Config {
  collections: {
    users: User
    media: Media
  }
}

export interface User {
  id: string
  email: string
  role: 'admin' | 'organizer'
  firstName: string
  lastName: string
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: string
  alt?: string
  updatedAt: string
  createdAt: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
}
